# .streamlit/main.yml
name: My Streamlit App
description: This is a description of my Streamlit app.

# Specify the Streamlit app file and any additional files/directories required by your app
# Replace 'app.py' with the filename of your Streamlit app
app:
  command:
    - streamlit run
    - pdf_compressor.py

# Specify the Streamlit version you are using (optional)
# If not specified, it will use the default Streamlit version on Streamlit Sharing
#streamlit_version: "1.0.0"

# Specify the dependencies required for your app
# You can specify the libraries needed by your app here
# For example, if you need pandas, uncomment the following line:
# dependencies:
   - PyMuPDF

# Specify any environment variables required for your app (optional)
#env:
#  MY_ENV_VAR: "my_value"
