name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.prashantjack1991 }}
        password: ${{ secrets.Prashant@32 }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: username/repo-name:latest # Replace 'username' and 'repo-name' with your Docker Hub username and desired image name

    - name: Deploy to Cloud Platform (e.g., AWS ECS, GCP Kubernetes Engine, etc.)
      # Add steps here to deploy the Docker image to your preferred cloud platform
